modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0-or-later"

[[mods]]
modId="sturdy_farmland_more_compat"
version="1.1"
displayName="Sturdy Farmland - More Farmland Compatibility"
description='''
Adds additional farmland and crop blocks to the tags
#dew_drop_farmland_growth:cancel_random_tick and #dewdrop:waterable
so Sturdy Farmland - Growth Edition and Dew Drop treat them like proper farmland.
'''
authors="CrypCee"

[[dependencies.sturdy_farmland_more_compat]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sturdy_farmland_more_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sturdy_farmland_more_compat]]
    modId="dew_drop_farmland_growth"
    mandatory=true
    versionRange="[5.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sturdy_farmland_more_compat]]
    modId="bots_lib"
    mandatory=true
    versionRange="[4.1.1,)"
    ordering="NONE"
    side="BOTH"
